# Generated by Django 5.2.4 on 2025-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='mails',
            name='name',
            field=models.CharField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(upload_to='topics'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
    ]
