# Generated by Django 5.2.4 on 2025-07-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0002_alter_mails_mail_alter_mails_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
    ]
